### ISSUE TITLE
Fix 'Unreachable code.' issue in commands\animeandmanga\User.js

### ISSUE THREAD

**Issue by hernikplays** [Atsukoro-bot/Atsukoro#3]
[CodeFactor](https://www.codefactor.io/repository/github/atsukoro-bot/atsukoro/overview/main) found an issue: Unreachable code.

It's currently on:
[commands\animeandmanga\User.js:582](https://www.codefactor.io/repository/github/atsukoro-bot/atsukoro/source/main/commands/animeandmanga/User.js#L582)

WHY USE BREAK WHEN YOU ALREADY HAVE RETURN O H MY G O D

**Comment by xHyroM** [comment]
https://github.com/Atsukoro-bot/Atsukoro/issues/4
